### ISSUE TITLE
Добавить конфигурацию

### ISSUE THREAD

**Issue by 7makes** [kochetkov-ma/allure-server#31]
Вывести в настройку допустимый размер загружаемого файла в UI

**Comment by kochetkov-ma** [comment]
Fixed
https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.3
Default size = 100MB = `spring.servlet.multipart.max-file-size` in application.properties
You may adjust it via Spring Config or [ENV_VAR](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables)  `spring_servlet_multipart_maxfilesize`

**Comment by kochetkov-ma** [comment]
Close after check please

**Comment by 7makes** [comment]
Fix work without  bubs

**Comment by konflic** [comment]
I think it is better to add this config line to docker-compose so that it would be easier to manage if no nothing about spring, java and so on. For those who find this thread as I did. This line works, crossed out lines does not provoke any error in spring, but does not increase upload size. I used dashes, but dashed should be removed.

![image](https://github.com/kochetkov-ma/allure-server/assets/44262112/9acfb506-5cd4-44ba-8507-b5dcea10c068)

**Comment by andridzi** [comment]
> Fixed https://github.com/kochetkov-ma/allure-server/releases/tag/v2.8.3 Default size = 100MB = `spring.servlet.multipart.max-file-size` in application.properties You may adjust it via Spring Config or [ENV_VAR](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.external-config.typesafe-configuration-properties.relaxed-binding.environment-variables) `spring_servlet_multipart_maxfilesize`

are you sure it works in latest `2.11.5` release?
tried env `spring_servlet_multipart_maxfilesize` and other variations - still getting error
```Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.multipart.MaxUploadSizeExceededException: Maximum upload size exceeded; nested exception is java.lang.IllegalStateException: org.apache.tomcat.util.http.fileupload.impl.SizeLimitExceededException: the request was rejected because its size (109858495) exceeds the configured maximum (104857600)] with root cause```
